version: "3"
services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    restart: unless-stopped
    depends_on:
      - sonarqube_db
    networks:
      - sonarqube_net
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled_plugins:/opt/sonarqube/lib/bundled-plugins
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
      - "9001:9001"
  sonarqube_db:
    image: postgres:latest
    container_name: sonarqube_db
    restart: unless-stopped
    networks:
      - sonarqube_net
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    ports:
      - "5432:5432"
    volumes:
      - sonarqube_db:/var/lib/postgresql
      - sonarqube_db_data:/var/lib/postgresql/data

networks:
  sonarqube_net:
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled_plugins:
  sonarqube_logs:
  sonarqube_db:
  sonarqube_db_data:
    
